theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "disk_space"
path = "/"
info_type = "used"
format = "{icon} ROOT: {used}/{total} ({available} free)"
alert = 80
warning = 60

[[block]]
block = "disk_space"
path = "/home/danielthorpe"
info_type = "used"
format = "{icon} HOME: {used}/{total} ({available} free)"
alert = 80
warning = 60

[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{average} avg"
chip = "coretemp-isa-*"
inputs = ["Package id 0"]

[[block]]
block = "net"
device = "wlan0"
format = "{ip} {speed_down;K*b} {graph_down;K*b}"
interval = 5

[[block]]
block = "external_ip"
format = "{ip} {country_code}"
interval = 3600


[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"

