theme = "modern"
icons = "awesome"

[[block]]
block = "disk_space"
path = "/"
info_type = "used"
format = "{icon} ROOT: {used}/{total} ({available} free)"
alert_absolute = true
unit = "GB"
alert = 50
warning = 40

[[block]]
block = "disk_space"
path = "/home/okami"
info_type = "used"
format = "{icon} HOME: {used}/{total} ({available} free)"
alert_absolute = true
unit = "GB"
alert = 50
warning = 40


[[block]]
block = "net"
device = "enp34s0"
format = "{ip} {speed_down;K*b} {graph_down;K*b}"
interval = 5

[[block]]
block = "external_ip"
format = "{ip} {country_code}"


[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"

